import type { Metadata } from "next";
import { Manufacturing_Consent, Noto_Serif, Open_Sans } from "next/font/google";

// import { Navbar } from "@/components/navbar";

import "./globals.css";

const manufacturingConsent = Manufacturing_Consent({
    variable: "--font-manufacturing-consent",
    weight: "400",
    subsets: ["latin"],
});

const openSans = Open_Sans({
    variable: "--font-open-sans",
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

const notoSerif = Noto_Serif({
    variable: "--font-noto-serif",
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    metadataBase: new URL("https://sonavagarwal.com"),
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${openSans.variable} ${manufacturingConsent.variable} ${notoSerif.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                {/* <Navbar /> */}
                <main className="flex-1">{children}</main>
            </body>
        </html>
    );
}
