import type { Metadata } from "next";
import { Manufacturing_Consent, Noto_Serif, Open_Sans } from "next/font/google";
import Link from "next/link";
import Script from "next/script";

// import { Navbar } from "@/components/navbar";

import "./globals.css";

const GOOGLE_ANALYTICS_ID = "G-E2XNDY9EVX";

const manufacturingConsent = Manufacturing_Consent({
    variable: "--font-manufacturing-consent",
    weight: "400",
    subsets: ["latin"],
    adjustFontFallback: false,
});

const openSans = Open_Sans({
    variable: "--font-open-sans",
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

const notoSerif = Noto_Serif({
    variable: "--font-noto-serif",
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    metadataBase: new URL("https://sonavagarwal.com"),
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${openSans.variable} ${manufacturingConsent.variable} ${notoSerif.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                {/* <Navbar /> */}
                <main className="flex-1">{children}</main>
                <footer className="mx-auto flex w-full items-center justify-center border-t border-neutral-200 bg-neutral-100 px-4 py-8 text-xs text-neutral-500 mt-32">
                    <Link
                        href="/privacy-policy/"
                        className="transition-colors hover:text-neutral-900"
                    >
                        Privacy policy
                    </Link>
                </footer>
                <Script
                    src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE_ANALYTICS_ID}`}
                    strategy="afterInteractive"
                />
                <Script id="google-analytics" strategy="afterInteractive">
                    {`
                        window.dataLayer = window.dataLayer || [];
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());
                        gtag('config', '${GOOGLE_ANALYTICS_ID}');
                    `}
                </Script>
            </body>
        </html>
    );
}
