// This file is generated by scripts/generate-articles.mjs.
// Do not edit it directly.

import * as graduation from "./graduation/page";

export const ARTICLES = {
    graduation,
} as const;

export type ArticleKey = keyof typeof ARTICLES;

export const ARTICLE_KEYS_BY_SLUG = {
    graduation: "graduation",
} as const satisfies Record<string, ArticleKey>;

export type ArticleSlug = keyof typeof ARTICLE_KEYS_BY_SLUG;
