// This file is generated by scripts/generate-articles.mjs.
// Do not edit it directly.

import * as bestMatchaInLa from "./best-matcha-in-la/page";
import * as foundations from "./foundations/page";
import * as graduation from "./graduation/page";
import * as janeStreet from "./jane-street/page";
import * as kyotoHinge from "./kyoto-hinge/page";
import * as nova from "./nova/page";
import * as poppin from "./poppin/page";
import * as retiredPersonalWebsite from "./retired-personal-website/page";

export const ARTICLES = {
    bestMatchaInLa,
    foundations,
    graduation,
    janeStreet,
    kyotoHinge,
    nova,
    poppin,
    retiredPersonalWebsite,
} as const;

export type ArticleKey = keyof typeof ARTICLES;

export const ARTICLE_KEYS_BY_SLUG = {
    "best-matcha-in-la": "bestMatchaInLa",
    foundations: "foundations",
    graduation: "graduation",
    "jane-street": "janeStreet",
    "kyoto-hinge": "kyotoHinge",
    nova: "nova",
    poppin: "poppin",
    "retired-personal-website": "retiredPersonalWebsite",
} as const satisfies Record<string, ArticleKey>;

export type ArticleSlug = keyof typeof ARTICLE_KEYS_BY_SLUG;
